### ISSUE TITLE
Add Custom time in previous dates

### ISSUE THREAD

**Issue by pascholynx** [TheAce74/TaskTabulator#5]
Make the app to be able to add Custom time in dates that have passed
![Screenshot (124)](https://github.com/TheAce74/TaskTabulator/assets/106701484/e8b9baee-79a4-47fe-9617-ec89781937b9)

**Comment by TheAce74** [comment]
Thank you for your feedback, I appreciate the fact that the app is useful to others including my wife 🚀

Check the site out, I've already added this feature in the last two sprints
