### ISSUE TITLE
Update Monthly Cumulative

### ISSUE THREAD

**Issue by pascholynx** [TheAce74/TaskTabulator#6]
The Monthly cycle begins from 19th of one month to 20th of the next month. Making the cumulative to be in this range will help in the calculation as the monthly cycle doesn't follow the normal month.

**Comment by TheAce74** [comment]
Wow, thank you. I didn't know that the monthly cycle worked like that. I only knew about the day starting by 1am instead of 12am and I created a custom day system.

Your input is greatly appreciated, I'll work on this in the next sprint

**Comment by TheAce74** [comment]
@pascholynx I just updated the monthly cumulative now; you can check it out. I'll be proceeding to settle issue #7
