### ISSUE TITLE
Add edit counter number directly

### ISSUE THREAD

**Issue by pascholynx** [TheAce74/TaskTabulator#7]
In the case of having to add a number in the hundreds, it will be best to just type in the number instead of clicking the plus button till it reaches the hundred.

**Comment by TheAce74** [comment]
Noted, will work on this as well. Let me tidy up the current task I'm handling and settle #6

**Comment by TheAce74** [comment]
As of PR #9, this enhancement has been added. Happy working, @pascholynx 

If you have any other issues, do well to reach out to me.
